name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag image with'
        required: true
        default: '0.0.1'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.version }}!"
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag my-image-name:${{ github.event.inputs.version }}
